# contents of environment.yml
name: opentargets-api-env
channels:
 - conda-forge
 - bioconda
dependencies:
 - pandas
 - xlwt
 - r-ghql
 - r-irkernel
 - ipykernel
 - bash_kernel
 - papermill
 - gcsfs==0.2.3
 - pip
 - pip: 
   - opentargets